### YamlMime:Role
title: 데이터 엔지니어
metadata:
  title: 데이터 엔지니어
  description: 데이터 엔지니어는 데이터 서비스의 전체 스택을 사용하여 데이터 관리, 모니터링, 보안과 개인 정보 보호 기능을 설계하고 구현합니다.
  ms.openlocfilehash: 27dda4816700425bba7bb9d02ba64b00d874373a
  ms.sourcegitcommit: 15832c0b302b429735730b73fbfd30bb4b3f0771
  ms.translationtype: MT
  ms.contentlocale: ko-KR
  ms.lasthandoff: 01/04/2022
  ms.locfileid: "135763446"
uid: role.data-engineer
summary: >
  데이터 엔지니어는 데이터 서비스의 전체 스택을 사용하여 데이터 관리, 모니터링, 보안과 개인 정보 보호 기능을 설계하고 구현합니다.
subTitle: 데이터 엔지니어는 데이터 서비스의 전체 스택을 사용하여 데이터 관리, 모니터링, 보안과 개인 정보 보호 기능을 설계하고 구현합니다.
certificationPaths:
- title: Azure 데이터 엔지니어
  linkedInKeywords: Azure data engineer
  uid: certification-path.azure-data-engineer
  prerequisites:
  - uid: certification.azure-fundamentals
    isOptional: true
    levels:
    - beginner
  - uid: certification.azure-data-engineer
    levels:
    - intermediate
certifications:
- uid: certification.azure-data-engineer
  requiredExams:
  - uid: exam.dp-203
- uid: certification.customer-data-platform-specialty
  requiredExams:
  - uid: exam.mb-260
resources:
- title: Microsoft 교육 및 인증 가이드
  description: 간결한 교육 및 인증 가이드에서 모든 인증을 탐색합니다.
  href: https://aka.ms/TrainingCertDeck
- title: 교육 및 인증 포스터
  description: 이 교육 및 인증 포스터를 통해 성공을 위한 길을 선택합니다.
  href: https://aka.ms/traincertposter
- title: 인증 지원
  href: ../help.md
  description: Microsoft Certification 지원 포럼에서 도움을 받으십시오. 포럼 조정자는 월요일에서 금요일까지 업무일 하루 만에 응답할 것입니다.
