### YamlMime:FAQ
metadata:
  title: 'FAQ: Learn에서 Learning Partner 과정 예약 | Microsoft Docs'
  description: 'FAQ: Learn에서 Learning Partner 과정 예약'
  documentationcenter: NA
  author: micsullivan
  ms.topic: article
  ms.tgt_pltfrm: NA
  ms.workload: NA
  ms.date: 09/01/2020
  ms.author: msulliv
  ms.prod: non-product-specific
  ms.openlocfilehash: f699b9754540f502f4b0dce9f4dc3b9a5ff2f733
  ms.sourcegitcommit: 9732383406c868d1279ca5ca79d423c5b99be073
  ms.translationtype: HT
  ms.contentlocale: ko-KR
  ms.lasthandoff: 09/14/2021
  ms.locfileid: "132111510"
title: 'FAQ: Learn에서 Learning Partner 과정 예약'
summary: "\n## <a name=\"instructor-led-training\"></a>강사가 진행하는 교육\n"
sections:
- name: 강사가 진행하는 교육
  questions:
  - question: >
      Microsoft Learning Partner 강사 지도식 교육 예약 서비스란 무엇입니까?
    answer: "Microsoft는 [**Microsoft Learn**](/learn)에 실시간 강사 지도식 교육 예약 기능을 제공함으로써 단순하고 간소화된 학습자 환경을 제공하고 있습니다. Microsoft Learn에서의 과정 예약 통합을 통해 학습자는 자격을 갖춘 Learning Partners가 제공하는 강사 지도식 교육 과정을 미리 볼 수 있습니다. 과정을 선택하면 Learning Partner 사이트로 직접 연결되고 여기서 등록 및 결제를 완료합니다.\n\n이 서비스는 현재 '공개 미리보기'이며 과정의 등록은 영어로만 시작할 수 있습니다. 추가 자격 Learning Partners는 다음 해에 추가될 예정입니다. \n"
  - question: >
      Learning Partner 강사 지도식 교육 예약 서비스에서 제공되는 과정은 무엇입니까?
    answer: >
      2020년 9월 22일부터 다음 과정의 예약 서비스가 가능합니다. 추가 과정은 Learning Partner에서 추가됨에 따라 추가될 예정입니다.


      1. Microsoft Azure Fundamentals (2 day)

      2. Microsoft Azure Fundamentals (1 day)

      3. Microsoft Azure 관리자

      4. Developing Solutions for Microsoft Azure

      5. Designing and Implementing an Azure AI Solution

      6. Azure에서 데이터 과학 솔루션 디자인 및 구현

      7. Designing an Azure Data Solution

      8. Implementing an Azure Data Solution

      9. Designing for Identity and Security

      10. Deploying and Configuring Infrastructure

      11. Microsoft Azure Architect Design

      12. Microsoft Azure 보안 기술

      13. Windows 10 설치

      14. Dynamics 365: Power Platform Applications

      15. Office 365 Management

      16. Managing Microsoft 365 Identity and Access

      17. 교실 및 온라인 교육 찾기
  - question: >
      Microsoft Learn을 사용하려면 프로필을 만들어야 하나요?
    answer: >
      아니요, 프로필을 만들 필요가 없습니다. 프로파일을 작성하지 않고도 온라인 학습 경로, [강사 지도식 과정 찾아보기](/learn/certifications/courses/browse/) 및 [국가 또는 지역별로 Microsoft Learning Partner 찾기](/learn/certifications/partners#find-a-microsoft-learning-partner-by-country)에 액세스하여 사용할 수 있습니다.


      Microsoft Learn에 대한 강사 지도식 교육 과정을 예약하면 선택한 Learning Partner의 사이트로 리디렉션되어 등록 및 결제를 완료합니다. Learning Partners를 사용하려면 해당 사이트에 로그인해야 할 수 있습니다.
  - question: >
      Microsoft Learn 프로필을 만들고 로그인할 때 사용할 수 있는 기능은 무엇입니까?
    answer: "- 학습 활동의 진행 상황 추적 \n- 모듈 컬렉션 만들기 및 공유 \n- 책갈피 저장 \n- 포인트 및 성과 내역 저장 \n- 별도 비용이 없는 Azure 리소스 사용 \n- 맞춤형 권장 사항 보기 \n"
  - question: "Microsoft Learning의 Learning Partner를 포함한 과정에 등록했지만 과정 확인을 받지 못했습니다.   어떻게 해야 합니까? \n"
    answer: "받은 편지함, 정크 메일 또는 스팸을 확인하여 등록한 과정의 Learning Partner로부터 온 이메일을 찾아보시기 바랍니다.  \n\n확인 메일을 여전히 찾을 수 없는 경우 수업을 예약한 Learning Partner에게 문의하십시오. Learning Partner는 메일 문제를 해결하거나 과정 등록의 유효성을 검사하는 데 도움을 줄 수 있습니다. Learning Partner 연락처 정보는 다음에서 찾을 수 있습니다. [국가 또는 지역별 Microsoft Learning 파트너 찾기](/learn/certifications/partners#find-a-microsoft-learning-partner-by-country)\n"
  - question: "과정에 등록 중이며 Learning Partner 사이트에 접속했지만 카트에 아무 것도 없습니다.   \n"
    answer: >
      해당 과정에 대해 선택한 Learning Provider에게 문의하여 문제를 해결하십시오. Learning Partner 연락처 정보는 다음에서 찾을 수 있습니다. [국가 또는 지역별 Microsoft Learning 파트너 찾기](/learn/certifications/partners#find-a-microsoft-learning-partner-by-country)
  - question: "과정을 취소하거나 일정을 변경해야 합니다.   \n"
    answer: >
      Learning Partner에게 직접 문의하십시오. Learning Partner 연락처 정보는 다음에서 찾을 수 있습니다. [국가 또는 지역별 Microsoft Learning 파트너 찾기](/learn/certifications/partners#find-a-microsoft-learning-partner-by-country)
  - question: "Learn 사이트에 표시된 가격이 체크아웃 시 표시된 가격과 동일하지 않았습니다. \n"
    answer: "Learn에 다른 금액이 표시되더라도 Learning Partner 사이트 또는 카트의 가격을 항상 항목의 가격으로 사용해야 합니다.  \n\nLearning Partner 사이트 또는 카트의 최종 가격은 이미 세금을 포함하거나 체크아웃 시 계산해야 하는 세금을 포함할 수 있으므로 다를 수 있습니다. 여기에는 판매세 및 부가가치세(VAT)가 포함될 수 있습니다. 지불하는 최종 금액은 또한 구매자의 위치 또는 과정의 언어에 따라 달라질 수 있습니다.  \n\n일부 Learning Partners는 체크아웃 과정에서 추가적인 서비스 기능을 제공할 수 있습니다. 이러한 서비스의 가격에 따라 체크아웃 시 표시되는 최종 가격이 변경될 수 있습니다.   \n"
  - question: "우리 나라나 지역의 과정은 언제 볼 수 있습니까?  \n"
    answer: >
      이것은 소수의 유자격 Learning Partners를 포함한 '공개 프리뷰'에서 출시한 새로운 서비스로서 여기서 기능을 테스트하고 과정을 세밀하게 조정합니다. 처음에는 과정 예약이 영어로만 진행되며 12개월 동안 추가 Learning Partners를 포함합니다.
  - question: >
      다른 교육 과정이 제가 원하는 교육 과정보다 다소 비싼 이유는 무엇입니까?
    answer: >
      모든 시장과 마찬가지로 수업료는 Learning Partner에 의해 결정됩니다. Partner는 Microsoft Learn 예약 도구에 나열된 가격에 대해 완전한 Microsoft 공식 과정 교육 경험을 제공해야 합니다. Partner는 선택에 따라 추가 제품 및 서비스를 광고할 수 있습니다. 광고 가격이 잘못되었거나 부정확하다고 생각될 경우 [Learn 지원 포럼의 Learning Partner 강사 지도식 과정 예약](https://trainingsupport.microsoft.com/en-us/iltvilt/forum)으로 문의해 주세요.
  - question: >
      과정 위치, 날짜 등에 의한 필터링이 제대로 작동하지 않습니다.
    answer: >
      필터링이 작동하지 않는 경우 브라우저를 새로 고침하고 다시 시도하십시오. 필터가 여전히 작동하지 않는다고 생각되는 경우 [Learn 지원 포럼의 Learning Partner 강사 지도식 과정 예약](https://trainingsupport.microsoft.com/en-us/iltvilt/forum)에서 질문을 할 수 있습니다. 이것은 도움을 검색 및 요청하고, 문제를 보고하고, 조언을 구할 수 있는 최고의 리소스입니다.
  - question: >
      내 영역에서 Learning Partner를 찾을 수 없습니다.
    answer: >
      찾고 있는 Learning Partner 또는 과정이 표시되지 않는 경우 Microsoft Learning에 표시된 것 외에 추가로 Learning Partner 사이트에서 날짜와 시간을 확인할 수 있습니다.  Learning Partners는 모든 수업 일정을 나열할 필요가 없습니다. [국가 또는 지역별 Microsoft Learning Partner 찾기](/learn/certifications/partners#find-a-microsoft-learning-partner-by-country)에서 모든 Microsoft Learning Partner 목록을 찾을 수 있습니다.


      이 새로운 서비스를 시작하면서 자격을 갖춘 Learning Partners의 수를 제한합니다. 향후 1년 동안 특정 기준을 충족하는 Learning Partners가 추가될 예정입니다.
  - question: >
      Learning Partner의 지원 채널을 검토해보았지만 아무런 응답도 받지 못했습니다.
    answer: >-
      Learning Partner는 자신의 사이트에서 일정 예약과 관련된 지원을 제공할 책임이 있습니다. Learning Partner의 웹 사이트를 찾아보고 다른 번호를 시도할 수 있습니다.


      여전히 Learning Partner에게 연락할 수 없는 경우 [Learn 지원 포럼의 Learning Partner 강사 지도식 과정 예약](https://trainingsupport.microsoft.com/en-us/iltvilt/forum)에 질문을 게시할 수 있습니다. 이것은 도움을 요청하고, 문제를 보고하고, 조언을 구할 수 있는 최고의 리소스입니다.
